config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'messages#index'
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	validates :title, length: {minimum: 5}, presence: true
	validates :content, length: {minimum: 15}, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def index
		@messages = Message.all.order("id desc")
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
		if @message.valid?
			@message.save
			@messages = Message.all.order("id desc")
			render json: {success: "Message #{@message.title} saved.", messages: @messages.to_json}
		else
			render json: {error: "Message can't created", errors: @message.errors}
		end
	end

  def update
  end

  def destroy
  	@message = Message.delete(params[:id])
  	if @message
  		redirect_to messages_path()
  	else
  		render :index
  	end
  end

  private

  def message_params
  	params.require(:message).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FtBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modalMessage">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add Message</h4>
      </div>
      <div class="modal-body">
        <%= form_for @message, html: {method: 'post', id: "formMessage"} do |f| %>
          <p>
            <%= f.label :title, "Title *" %>
            <%= f.text_field :title, {required: true} %>
          </p>
          <p>
            <%= f.label :content, "Content *" %>
            <%= f.text_field :content, {required: true} %>
          </p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" id="save" class="btn btn-primary">Save</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/messages/index.html.erb
<div class="container-fluid">
	<div class="row" style="text-align: center;">
		<div class="col-lg-12">
			<h2>
				<a href=<%= new_message_path() %> data-toggle='modal' data-target='#modalMessage'>
					<span class="glyphicon glyphicon-plus"></span> Add message
				</a>
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<% if @messages.count > 0 %>
				<div id="carousel" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <ol class="carousel-indicators">
						<% @messages[0..4].each_with_index do |message, i| %>
				    	<li data-target="#carousel" data-slide-to="<%= i %>" class="<%= 'active' if i.eql?(0) %>"></li>
						<% end %>
				  </ol>

				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
						<% @messages.each_with_index do |message, i| %>
							<% url = "https://dummyimage.com/800x400/eee/&text=#{message.title}" %>
							<div class="item <%= 'active' if i.eql?(0) %>">
								<img alt="<%= message.title %>" data-src="<%= url %>" src="<%= url %>" data-holder-rendered="true">

	  						<div class="carousel-caption">
	  							<p><%= message.content %></p>
	  						</div>
							</div>
						<% end %>
				  </div>

				  <!-- Controls -->
				  <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>

				<div id="archives">
					<table class="table table-responsive table-striped">
						<thead>
							<tr>
								<td>Title</td>
								<td>Content</td>
								<td>Actions</td>
							</tr>
						</thead>
						<tbody>
							<% @messages.each do |message| %>
								<tr>
									<td><%= message.title %></td>
									<td><%= message.content %></td>
									<td>
										<p><a href="<%= message_path(message.id) %>" data-method="delete" confirm="Are you sur to delete this message ?"><span class="glyphicon glyphicon-trash"></span></a></p>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			<% else %>
			None
			<% end %>
		</div>
	</div>
</div>


<%= render partial: 'modal', includes: {message: @message} %>